// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: goout/erajol_bike.proto

package protobufgoout

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ErajolBikeClient is the client API for ErajolBike service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ErajolBikeClient interface {
	OrderDriver(ctx context.Context, in *ReqErajolBikeOrderDriver, opts ...grpc.CallOption) (*ResErajolBikeOrderDriver, error)
}

type erajolBikeClient struct {
	cc grpc.ClientConnInterface
}

func NewErajolBikeClient(cc grpc.ClientConnInterface) ErajolBikeClient {
	return &erajolBikeClient{cc}
}

func (c *erajolBikeClient) OrderDriver(ctx context.Context, in *ReqErajolBikeOrderDriver, opts ...grpc.CallOption) (*ResErajolBikeOrderDriver, error) {
	out := new(ResErajolBikeOrderDriver)
	err := c.cc.Invoke(ctx, "/ErajolBike/OrderDriver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ErajolBikeServer is the server API for ErajolBike service.
// All implementations must embed UnimplementedErajolBikeServer
// for forward compatibility
type ErajolBikeServer interface {
	OrderDriver(context.Context, *ReqErajolBikeOrderDriver) (*ResErajolBikeOrderDriver, error)
	mustEmbedUnimplementedErajolBikeServer()
}

// UnimplementedErajolBikeServer must be embedded to have forward compatible implementations.
type UnimplementedErajolBikeServer struct {
}

func (UnimplementedErajolBikeServer) OrderDriver(context.Context, *ReqErajolBikeOrderDriver) (*ResErajolBikeOrderDriver, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderDriver not implemented")
}
func (UnimplementedErajolBikeServer) mustEmbedUnimplementedErajolBikeServer() {}

// UnsafeErajolBikeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ErajolBikeServer will
// result in compilation errors.
type UnsafeErajolBikeServer interface {
	mustEmbedUnimplementedErajolBikeServer()
}

func RegisterErajolBikeServer(s grpc.ServiceRegistrar, srv ErajolBikeServer) {
	s.RegisterService(&ErajolBike_ServiceDesc, srv)
}

func _ErajolBike_OrderDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqErajolBikeOrderDriver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErajolBikeServer).OrderDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ErajolBike/OrderDriver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErajolBikeServer).OrderDriver(ctx, req.(*ReqErajolBikeOrderDriver))
	}
	return interceptor(ctx, in, info, handler)
}

// ErajolBike_ServiceDesc is the grpc.ServiceDesc for ErajolBike service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ErajolBike_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ErajolBike",
	HandlerType: (*ErajolBikeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderDriver",
			Handler:    _ErajolBike_OrderDriver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goout/erajol_bike.proto",
}
